### PR TITLE
Recent fixes

### PR DESCRIPTION
**Pull request by nzakas**
Various fixes and merges from other pull requests.

### CODE REVIEW

**Comment by lsmith** [comment]
Thanks Nicholas. I'll process this now.

**Comment by lsmith** [comment]
Urg.  My mistake. I thought this was against the yui3 repo.  I don't have access to the yuitest repo yet.  Ryan or I will try again tomorrow after wrestling some permissions from Dav.

In the mean time, I noticed your yui3 repo fork hasn't yet had its tags purged.  Would you mind running this shell script? https://gist.github.com/1130822

The tag pool is shared by all forks, so every fork that gets untagged makes _every_ fork faster to push and pull.  Thanks!

**Comment by nzakas** [comment]
I'm actually just going to re-fork. I think my stuff is too far out of date to be useful at this point.

**Comment by lsmith** [comment]
I don't know if it's possible or easy to delete a fork and refork with the same name.  I admit I'm concerned that deleting the fork through the web interface will leave something behind with tags in tact.  Can you try the script on your fork before you try to delete and refork?

**Comment by nzakas** [comment]
Script exited with an error when I tried. The new fork became nzakas/yui3-1, so no relation to anything previously.

**Comment by lsmith** [comment]
Thanks for trying.  I've seen the yui3-1 thing before, which is why I was afraid your original yui3 is still lying around somewhere with all the tags polluting the global object pool.

**Comment by rgrove** [comment]
I don't suppose you remember what the error was?

**Comment by nzakas** [comment]
Negative, just went into workaround mode. I do remember it output "Cleaning up tags", listed all of the available tags, and then kablooey.

**Pull request merged**
